generate:
	go generate ./parsers/...

# clean the extra files generated by antlr4.
clean-extras:
	cd parsers && find . -type f \( -name '*.jar' -or -name '*.interp' -or -name '*.tokens' \) -delete

# clean all generated files.
clean: clean-extras
	cd parsers && find . -type f \( -name 'wdl*.go' \) -delete
