# Generate parsers for all WDL versions.
generate:
	go generate ./parsers/...

# Clean the extra files generated by ANTLR4 that are not needed by gowdl.
clean-extras:
	cd parsers && find . -type f \( -name '*.jar' -or -name '*.interp' -or -name '*.tokens' \) -delete

# Clean all generated files.
clean: clean-extras
	cd parsers && find . -type f \( -name 'wdl*.go' \) -delete
